# Generated by Django 3.1.7 on 2021-03-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_post_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vid',
            field=models.CharField(default='v2X4vdNwIPU', max_length=20),
        ),
    ]
